# Generated by Django 3.2.5 on 2021-07-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_club_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_profile',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
