# Generated by Django 3.2.5 on 2021-07-10 18:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_club_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_profile',
            name='profile_pic',
            field=models.ImageField(default='profile_imgs/default.jpg', upload_to=api.models.upload_path),
        ),
    ]
