# Generated by Django 3.2.5 on 2021-07-10 19:25

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_club_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to=api.models.upload_path),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=250, unique=True)),
                ('event_desc', models.TextField(max_length=1000)),
                ('poster', models.ImageField(default='default.jpg', upload_to=api.models.upload_path_event)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
