# Generated by Django 3.2.5 on 2021-07-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_events_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_desc',
            new_name='event_description',
        ),
    ]
