# Generated by Django 3.2.5 on 2021-07-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_club_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_profile',
            name='tag_line',
            field=models.CharField(default='', max_length=500),
        ),
    ]
