# Generated by Django 3.2.5 on 2021-07-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='club_name',
            field=models.CharField(max_length=150),
        ),
    ]
