# Generated by Django 3.2.5 on 2021-07-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_event_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
