# Generated by Django 3.2.5 on 2021-07-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_event_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='rejected',
            new_name='visible',
        ),
        migrations.AlterField(
            model_name='event',
            name='approved',
            field=models.IntegerField(default=0),
        ),
    ]
