# Generated by Django 3.2.5 on 2021-07-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_register_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_event',
            name='event_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
