# Generated by Django 3.2.5 on 2021-07-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_register_event_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='club_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.club_profile'),
        ),
    ]
