# Generated by Django 3.2.5 on 2021-07-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210719_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='to_announce',
            field=models.CharField(default='', max_length=250),
        ),
    ]
