# Generated by Django 3.2.5 on 2021-07-19 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_announcement_to_announce'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date_srt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='date_srt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='register_event',
            name='date_srt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
