# Generated by Django 3.2.5 on 2021-07-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_announcement_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_event',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
    ]
