# Generated by Django 3.2.5 on 2021-07-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_event_view_count_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
