# Generated by Django 3.2.5 on 2021-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_announcement_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='document1',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='document2',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
