from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from rest_framework import routers
from .views import (
    UserViewSet, 
    UserViewSet_club, 
    BookViewSet, 
    ObtainAuthToken, 
    get_data_user, 
    VerificationView, 
    club_data, 
    club_data_create, 
    clubs_all, 
    event_create, 
    events_all,
    events_all_admin,
    events_club,
    member_add,
    member_delete,
    club_profile,
    Event_register,
    Event_unregister,
    Registered_users,
    event_update,
    event_data_id,
    Is_registered,
    Is_member,
    get_type_user,
    announcement,
    get_announcements,
    uncompleted_events,
    get_announcement_club,
    get_all_announcements,
    rating,
    club_delete,
    approval,
    Event_view,
    stats_of_event,
    check_in_true,
    check_in_false,
    events_club_cal,
    event_delete_id,
    stats_of_club,
    )

router = routers.DefaultRouter()
router.register('books', BookViewSet)
# router.register('users', UserViewSet.as_view())

urlpatterns = [
    path('', include(router.urls)),
    # url(r'^api/api-token-auth/', obtain_auth_token),
    path('users', UserViewSet.as_view({'get': 'list'})),
    path('clubs', UserViewSet_club.as_view({'get': 'list'})),
    path('club/club_delete', club_delete.as_view()),
    path('login', ObtainAuthToken.as_view()),
    path('user/get_info', get_data_user.as_view()),
    path('user/get_type_user', get_type_user.as_view()),
    path('activate/<uidb64>/<token>', VerificationView.as_view(), name='activate'),
    path('club/profile_club_create', club_data_create.as_view()),
    path('club/event_create', event_create.as_view()),
    path('club/event_update', event_update.as_view()),
    path('club/clubs_all', clubs_all.as_view()),
    path('club/approval', approval.as_view()),
    path('club/event_data_id', event_data_id.as_view()),
    path('club/profile_club/<club_name>', club_data.as_view()),
    path('club/club_profile', club_profile.as_view()),
    path('club/events', events_club.as_view()),
    path('club/events_club_cal/<club_name>', events_club_cal.as_view()),
    path('club/uncompleted_events/<club_name>', uncompleted_events.as_view()),
    path('club/events_all', events_all.as_view()),
    path('club/events_all_admin', events_all_admin.as_view()),
    path('club/member_add', member_add.as_view()),
    path('club/member_delete', member_delete.as_view()),
    path('club/event_register', Event_register.as_view()),
    path('club/event_unregister', Event_unregister.as_view()),
    path('club/is_registered', Is_registered.as_view()),
    path('club/is_member', Is_member.as_view()),
    path('club/registered_users/<event_name>', Registered_users.as_view()),
    path('club/announcement', announcement.as_view()),
    path('club/event_view', Event_view.as_view()),
    path('club/check_in_true', check_in_true.as_view()),
    path('club/check_in_false', check_in_false.as_view()),
    path('club/stats_of_event', stats_of_event.as_view()),
    path('club/stats_of_club', stats_of_club.as_view()),
    path('club/event_delete_id', event_delete_id.as_view()),
    path('club/get_announcements', get_announcements.as_view()),
    path('club/get_all_announcements', get_all_announcements.as_view()),
    path('club/get_announcement_club/<club_name>', get_announcement_club.as_view()),
    path('user/rating', rating.as_view()),
]